### ISSUE TITLE
Error message "The data cannot be displayed" when accessing the DB2 database in console

### ISSUE THREAD

**Issue by lee-zhg** [IBM-Cloud/slack-chatbot-database-watson#10]
After creating DB2 database by executing "ibmcloud resource service-instance-create eventDB dashdb-for-transactions free us-south" command, received Error message "The data cannot be displayed" when accessing the DB2 database in console.

When the DB2 database is created in IBM Cloud console, it is ok.

**Comment by data-henrik** [comment]
@lee-zhg I just tried creating the eventDB using CLI. Thereafter, with the service created, I switched to the console and the resource overview. From there I clicked to the Db2 service details and launched the Db2 on Cloud management console.

In the management console, I was able to create a table, insert data and select it.

Could you retry or add more details?

**Comment by data-henrik** [comment]
See my comment in #11. It seems your provisioning failed somehow. Please delete it and create it again. I am closing this issue. Please reopen if additional help is needed.

**Comment by lee-zhg** [comment]
@data-henrik I tested it multiple times and got the same result. It appears that the command below needs revision.

     "ibmcloud resource service-instance-create eventDB dashdb-for-transactions free us-south"

If the database is created via UI, everything works.

Thank you

**Comment by data-henrik** [comment]
@lee-zhg Does the command cause any error message? I tested it as printed in us-south. See
![image](https://user-images.githubusercontent.com/8414748/95986663-a84b8600-0e26-11eb-877e-74101b7f677a.png)

Thereafter, I went to https://cloud.ibm.com/resources and from there clicked through to the Db2 console.

**Comment by lee-zhg** [comment]
The command did not fail and it created a database instance. But, I can't access the database console via UI.

**Comment by data-henrik** [comment]
Have you deleted the instance and recreated it again? Do you go to the resources page, then click on eventDB and then on the console link?

**Comment by lee-zhg** [comment]
Yes, I did all that multiple times. If you are interested, I can go over the process with you in the next couple of hours or next Tuesday.

This morning I run everything again in IBM Cloud Shell as you did not encounter the same issue. And, I got the same result as I did on my local machine yesterday.

Could you please try it in Cloud Shell? It can ensure we run the process in the same environment. I feel we may have a diff CLI env as we see diff result.

**Comment by data-henrik** [comment]
Works for me in IBM Cloud Shell:
![image](https://user-images.githubusercontent.com/8414748/96017317-28371780-0e4a-11eb-9a31-11175fcdbf40.png)

And I can get to the created Db2 service and its management console. 

Could you open a support case? It might need debugging of your account.

**Comment by lee-zhg** [comment]
@data-henrik, I did more digging today and the instance of my DB2 instance does not have "dsn" element. It's why "dsn=params.__bx_creds[Object.keys(params.__bx_creds)[0]].dsn;" returns undefined.

I checked in us-east and us-south. If you create a new db2 instance and its credential, do you have "dsn" element? If you do, my cloud account have serious problem. If it works for you in diff region, could you please let me know too. I like to see it works.

BTW, I opened a ticket and asked what happened to "dsn".

Thank you

**Comment by data-henrik** [comment]
How do your credentials look like (structure)?

**Comment by lee-zhg** [comment]
The new credential and the old one are dramatically different. Below are the example of new one. I tested with 2 accounts.

{
  "apikey": "someKey",
  "connection": {
    "cli": {
      "arguments": [
        [
          "-u",
          "ieamqphm",
          "-p",
          "1DQPPT45QCJTzZ7S",
          "--ssl",
          "--sslCAFile",
          "9e529eec-97df-4574-8839-989d191c6c13",
          "--authenticationDatabase",
          "admin",
          "--host",
          "ad3cdab8-a740-ac15dbcc32cc.w0uv9tsomi9ig.databases.appdomain.cloud:32690"
        ]
      ],
      "bin": "db2",
      "certificate": {
        "certificate_base64": "LS0tLS1CRUdJTiBDRVJUSUZJQ0WNNQm9HQTFVRUF3d1RTVUpOSUVOc2IzVmtJRVJoZEdGaVlYTmxjekFlRncweU1EQTRNRFF3TWpReApNak5hRncwek1EQTRNREl3TWpReE1qTmFNQjR4SERBYUJnTlZCQU1NRTBsQ1RTQkRiRzkxWkNCRVlYUmhZbUZ6ClpYTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEWFVmTjRFQXBOMFc4a0VldnkKUTgxSUdQcmtaaGpoTDdISXhEVFBDNlM3dVhXYjN1YTJxOFJVVC8zd2ZQOWdubS9LZ0pjUmd3TWxtMFFQUFBpeAowYkhwSW9OVTJscVE1NkgxS0I2WkV1QkxSVFVaakFBL3Q5K3dIRFE4VFhLQjJtWCtKTzd4T2M5NFF0R0tTV0dRCkh6VGcyZ1BlbEtNaHV3SXZ6MXcyNzZOR3pwb3VPeTZTNVlWQm9CUFNEV21ZWnZFaUZqVDZHcmo2ZUxaR0hSOW8KMkVJdFZtTkd1eXFZNGZRQ3hYeGhoajdEdGhnTitoTDhVSWp1VUxwREZ3aUltdXFrL0NPb29uYngrL3lBVEFEWApqdWxETXQrYnZQR1JkaHBSMEg0YytTR0dubjFNSTNyZDRGU0tSbVE3eXVKR0txYjJqTTVhUS9HbjlBMUc4TEhGCnlicTNBZ01CQUFHalV6QlJNQjBHQTFVZERnUVdCQlJjdXhKVkVQTTQycnJJT2NnTXJQSllCbmg2NXpBZkJnTlYKSFNNRUdEQVdnQlJjdXhKVkVQTTQycnJJT2NnTXJQSllCbmg2NXpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1VtRmlRRzN4NzlxUHZQV3ovTi9Ic25PSFIvSmtEODBCVWdYMXNIblFoCmlkYkpBa2t5WjBsdVNBd3MvazhNNmF2N1NlV29qNGIvVGQ3K1dIVmxLMzNQczR4KzZqc3VXWURFL1RPeUFSQ00KcEpmSENqcU1LVElIN3VIQk4rNnBGUkVhN0VzZTRqNEY0SEpJU1A5Zzl0YzdieDFpcEVsUnU0cnlkVTYwWExYVgpjQytNQjYvV05LMHRtQ29UekhIeVVSeDRZR1Y5bzFPL2owS3BFNW4yQkVtUDFGd0JwNytYMnZwNTd4TkR5K1M0CmIreDkwSzdTMEI4VkNmUnNVRjZ5SVdpK1lORHZITms4U0ZXQXJQUG1nZU5rQUkydHE5VUtBZExtWkJ2R0llbHoKeElTUW53NXlDQmpueFZSdFZnM2ZuaW9vMHhiWnFJU1JrUTg1MTdTdXY4MnYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=",
        "name": "9e529eec-97df-4574-8839-989d191c6c13"
      },
      "composed": [
        "db2 -u ieamqphm -p 1DQTzZ7S --ssl --sslCAFile 9e529eec-97df-4574-8839-989d191c6c13 --authenticationDatabase admin --host ad3cdab8-abbe-4cbdbcc32cc.bs2ipa9ig.databases.appdomain.cloud:32690"
      ],
      "environment": {},
      "type": "cli"
    },
    "db2": {
      "authentication": {
        "method": "direct",
        "password": "1DQP5QC",
        "username": "ieamqphm"
      },
      "certificate": {
        "certificate_base64": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIVENDQWdXZ0F3SUJBZ0lVV2lJMTJEeG9kWmpMb05oVUxEUkp5a25sYk5zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hqRWNNQm9HQTFVRUF3d1RTVUpOSUVOc2IzVmtJRVJoZEdGaVlYTmxjekFlRncweU1EQTRNRFF3TWpReApNak5hRncwek1EQTRNREl3TWpReE1qTmFNQjR4SERBYUJnTlZCQU1NRTBsQ1RTQkRiRzkxWkNCRVlYUmhZbUZ6ClpYTXdnZ0VmTjRFQXBOMFc4a0VldnkKUTgxSUdQcmtaaGpoTDdISXhEVFBDNlM3dVhXYjN1YTJxOFJVVC8zd2ZQOWdubS9LZ0pjUmd3TWxtMFFQUFBpeAowYkhwSW9OVTJscVE1NkgxS0I2WkV1QkxSVFVaakFBL3Q5K3dIRFE4VFhLQjJtWCtKTzd4T2M5NFF0R0tTV0dRCkh6VGcyZ1BlbEtNaHV3SXZ6MXcyNzZOR3pwb3VPeTZTNVlWQm9CUFNEV21ZWnZFaUZqVDZHcmo2ZUxaR0hSOW8KMkVJdFZtTkd1eXFZNGZRQ3hYeGhoajdEdGhnTitoTDhVSWp1VUxwREZ3aUltdXFrL0NPb29uYngrL3lBVEFEWApqdWxETXQrYnZQR1JkaHBSMEg0YytTR0dubjFNSTNyZDRGU0tSbVE3eXVKR0txYjJqTTVhUS9HbjlBMUc4TEhGCnlicTNBZ01CQUFHalV6QlJNQjBHQTFVZERnUVdCQlJjdXhKVkVQTTQycnJJT2NnTXJQSllCbmg2NXpBZkJnTlYKSFNNRUdEQVdnQlJjdXhKVkVQTTQycnJJT2NnTXJQSllCbmg2NXpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1VtRmlRRzN4NzlxUHZQV3ovTi9Ic25PSFIvSmtEODBCVWdYMXNIblFoCmlkYkpBa2t5WjBsdVNBd3MvazhNNmF2N1NlV29qNGIvVGQ3K1dIVmxLMzNQczR4KzZqc3VXWURFL1RPeUFSQ00KcEpmSENqcU1LVElIN3VIQk4rNnBGUkVhN0VzZTRqNEY0SEpJU1A5Zzl0YzdieDFpcEVsUnU0cnlkVTYwWExYVgpjQytNQjYvV05LMHRtQ29UekhIeVVSeDRZR1Y5bzFPL2owS3BFNW4yQkVtUDFGd0JwNytYMnZwNTd4TkR5K1M0CmIreDkwSzdTMEI4VkNmUnNVRjZ5SVdpK1lORHZITms4U0ZXQXJQUG1nZU5rQUkydHE5VUtBZExtWkJ2R0llbHoKeElTUW53NXlDQmpueFZSdFZnM2ZuaW9vMHhiWnFJU1JrUTg1MTdTdXY4MnYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=",
        "name": "9e529eec-97df-4574-8839-989d191c6c13"
      },
      "composed": [
        "db2://ieamqphm:1DQPPT@ad3cdab8-abbe-4cb0-a740-ac15dbcc32cc.bs2ipa7w0uv9tsomi9ig.databases.appdomain.cloud:32690/bludb?authSource=admin&replicaSet=replset"
      ],
      "database": "bludb",
      "host_ros": [
        "ad3cdab8-abbe-4cb0-a740-ac15dbcc32cc.bs2ipa7w0uv9tsomi9ig.databases.appdomain.cloud:32631"
      ],
      "hosts": [
        {
          "hostname": "ad3cdab8-abbe-4cb0-a740-ac15dbcc32cc.bs2ipa7w0uv9tsomi9ig.databases.appdomain.cloud",
          "port": 32690
        }
      ],
      "jdbc_url": [
        "jdbc:db2://ad3cdab8-abbe-4cb0-a740-ac15dbcc32cc.bs2ipa7w0uv9tsomi9ig.databases.appdomain.cloud:32690/bludb:user=<userid>;password=<your_password>;sslConnection=true;"
      ],
      "path": "/bludb",
      "query_options": {
        "authSource": "admin",
        "replicaSet": "replset"
      },
      "replica_set": "replset",
      "scheme": "db2",
      "type": "uri"
    }
  },
  "iam_apikey_description": "Auto-generated for key 076fca5a-1af1-42e3-9844-20fcc51143c3",
  "iam_apikey_name": "Service credentials-1",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/e65910fa61ce9072d64902d03f3d4774::serviceid:ServiceId-94a0deb8-95e9-4a68-85f5-2e5a45094609",
  "instance_administration_api": {
    "deployment_id": "crn:v1:bluemix:public:dashdb-for-transactions:us-east:a/e65910fa61ce9072d64902d03f3d4774:ad3cdab8-abbe-4cb0-a740-ac15dbcc32cc::",
    "instance_id": "crn:v1:bluemix:public:dashdb-for-transactions:us-east:a/e65910fa61ce9072d64902d03f3d4774:ad3cdab8-abbe-4cb0-a740-ac15dbcc32cc::",
    "root": "https://api.us-east.db2.cloud.ibm.com/v4/ibm"
  }
}

**Comment by lee-zhg** [comment]
BTW, the db2 service is messed up in us-south yesterday. I had to use us-east.

**Comment by data-henrik** [comment]
Yes, that looks different from the credentials structure so far and from what is documented.

**Comment by data-henrik** [comment]
Ok, it seems there was an update to the docs with a distinction between legacy and new Enterprise and Standard plan: https://cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-connect_options

I am reopening this issue. It needs to be addressed in the code and in the tutorial

**Comment by lee-zhg** [comment]
@data-henrik DB2 support team confirmed that Standard DB2 does not come with dsn in its credential. It must be built manually.

I am sending a PR with code changes

**Comment by data-henrik** [comment]
addressed by #12
