### ISSUE TITLE
db2Setup fails because resource-controller.ibm.com: no such host

### ISSUE THREAD

**Issue by nddao** [IBM-Cloud/slack-chatbot-database-watson#3]
ibmcloud fn service bind dashDB slack/db2Setup  --instance eventDB
error: Unable to query services of the target resource group 'da4eeb910056460aa153f13b1352e661':
 Get https://resource-controller.ibm.com/v1/resource_instances?resource_group_id=da4eeb910056460aa153f13b1352e661&resource_id=&resource_plan_id=: dial tcp: lookup resource-controller.ibm.com: no such host

**Comment by data-henrik** [comment]
Can you confirm that it is still a problem and wasn't a temporary network issue? Are you on the latest CLI version and cloud functions plugin version? What IBM Cloud region are you using?

**Comment by nddao** [comment]
It is network issue.  Since it complaints the host resource-controller.ibm.com, I tried to ping it from the commane line, and got that host resource-controller.ibm.com is an unknown host as below

db2inst2@svlxdbp2:~/IRWW400> ping resource-controller.ibm.com
ping: unknown host resource-controller.ibm.com

**Comment by data-henrik** [comment]
Currently, in some environments, there is a problem with the cloud functions plugin (`ibmcloud fn`) because of the naming changes from bluemix.net to cloud.ibm.com. 

Here is a workaround: https://stackoverflow.com/questions/54610580/wrong-resource-controller-url-when-binding-a-service-to-a-cloud-function

I am following up with the cloud functions team to find out when the fix will be released.

**Comment by nddao** [comment]
It is network issue.  Since it complaints the host resource-controller.ibm.com, I tried to ping it from the commane line, and got that host resource-controller.ibm.com is an unknown host as below

db2inst2@svlxdbp2:~/IRWW400> ping resource-controller.ibm.com
ping: unknown host resource-controller.ibm.com

**Comment by nddao** [comment]
Work around solution works OK
https://stackoverflow.com/questions/54610580/wrong-resource-controller-url-when-binding-a-service-to-a-cloud-function.
Thanks
