### ISSUE TITLE
Can't get step 4 to work

### ISSUE THREAD

**Issue by vbaruchello** [IBM-Cloud/slack-chatbot-database-watson#9]
Hi, I can get everything 'working fine' as advised, including Slack - Watson Assistant integration. But I can't get 'step 4' to work. Basically, when I type 'help' in slack, just nothing happens. I can't even access any logging/monitoring information to see if my watson assistant is being reached.... Please advise. thanks

**Comment by data-henrik** [comment]
@vbaruchello Is that in a direct chat with the bot?

**Comment by vbaruchello** [comment]
I've tried it all - within the 'App', within the channel I linked to the app...

**Comment by vbaruchello** [comment]
> @vbaruchello Is that in a direct chat with the bot?

@data-henrik both, direct chat with bot (app) and slack channel connected with the app

**Comment by data-henrik** [comment]
In your Skill, go to Analytics and User Conversations. It should show if there was some activity.
From your description it seems that the integration is not fully working.

**Comment by vbaruchello** [comment]
we're getting there, thanks a lot.
 
From the metrics I can see the counter increments each time I type 'help' in the app in slack. But then why am I getting no response?
 
Thanks,
  Vincent

**Comment by vbaruchello** [comment]
found the root cause, coming from OAuth token udpates.
